export const GET_PLACES_REQUESTED = 'GET_PLACES_REQUESTED';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILED = 'GET_PLACES_FAILED';

export const GET_GEOCODE_REQUESTED = 'GET_GEOCODE_REQUESTED';
export const GET_GEOCODE_SUCCESS = 'GET_GEOCODE_SUCCESS';
export const GET_GEOCODE_FAILED = 'GET_GEOCODE_FAILED';

